// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, World!");

console.log("hello Rescript");

var d = 4.2 + 1.2;

console.log(d);

var a = "hello";

var b = 4234;

var c = 4.2;

exports.a = a;
exports.b = b;
exports.c = c;
exports.d = d;
/*  Not a pure module */
