// Generated by ReScript, PLEASE EDIT WITH CARE


console.log("Hello, World!");

console.log("hello Rescript");

var d = "newd";

console.log("b: int");

console.log("number");

var cond = {
  contents: true
};

console.log(cond);

console.log(typeof d);

cond.contents = false;

cond.contents = true;

function add(a, b) {
  return a + b | 0;
}

function minus(a, b) {
  return a - b | 0;
}

var Int = {
  add: add,
  minus: minus
};

console.log(3);

console.log(undefined);

var a = 2;

console.log("a = ");

console.log("a = " + a.toString());

var b = 4234;

var c = 4.2;

var cc;

export {
  b ,
  c ,
  d ,
  cond ,
  Int ,
  cc ,
  a ,
}
/*  Not a pure module */
