// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LeaferUi from "leafer-ui";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";

var leafer = new LeaferUi.Leafer({
      view: window,
      width: 600,
      height: 400
    });

var x_offset = [
  850,
  894,
  938,
  982,
  1026
];

var fillContainer = [];

function fillx(x1) {
  var f_offset = {
    x: -x1 | 0,
    y: 2
  };
  var f = {
    type: "image",
    url: "./src/dragon.png",
    mode: "clip",
    offset: f_offset
  };
  fillContainer.push(f);
}

x_offset.forEach(fillx);

fillContainer.forEach(function (x) {
      console.log(x);
    });

console.log(LeaferUi.AnimateEvent.FRAME);

var rectCurrent = new LeaferUi.Rect({
      x: 100,
      y: 100,
      width: 39,
      height: 56,
      fill: fillContainer[0],
      draggable: true
    });

leafer.add(rectCurrent);

var flag = {
  contents: 0
};

var flagTimeUp = {
  contents: false
};

var flagMove = {
  contents: false
};

setInterval((function (param) {
        flagTimeUp.contents = true;
        console.log("time up!");
      }), 200);

function rectUpdate(param) {
  if (flagTimeUp.contents === true) {
    flagTimeUp.contents = false;
    flag.contents = Caml_int32.mod_(flag.contents + 1 | 0, fillContainer.length);
    var fill = fillContainer[flag.contents];
    rectCurrent.fill = fill;
    console.log("run update");
  }
  if (flagMove.contents === true) {
    rectCurrent.x = rectCurrent.x + 1 | 0;
    return ;
  }
  
}

leafer.on_(LeaferUi.AnimateEvent.FRAME, (function (param) {
        rectUpdate(undefined);
      }));

function appname(param) {
  return "my name is dragon";
}

function moveDragon(param) {
  flagMove.contents = true;
  setTimeout((function (param) {
          flagMove.contents = false;
        }), 4000);
}

moveDragon(undefined);

var rectTimeDuration = 200;

export {
  leafer ,
  x_offset ,
  fillContainer ,
  fillx ,
  rectCurrent ,
  flag ,
  flagTimeUp ,
  flagMove ,
  rectTimeDuration ,
  rectUpdate ,
  appname ,
  moveDragon ,
}
/* leafer Not a pure module */
