// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LeaferUi from "leafer-ui";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";

var leafer = new LeaferUi.Leafer({
      view: window,
      width: 600,
      height: 400
    });

var x_offset = [
  850,
  894,
  938,
  982,
  1026
];

var fillContainer = [];

function fillx(x1) {
  var f_offset = {
    x: -x1 | 0,
    y: 2
  };
  var f = {
    type: "image",
    url: "dragon.png",
    mode: "clip",
    offset: f_offset
  };
  fillContainer.push(f);
}

x_offset.forEach(fillx);

fillContainer.forEach(function (x) {
      console.log(x);
    });

console.log(LeaferUi.AnimateEvent.FRAME);

var rectCurrent = new LeaferUi.Rect({
      x: 0,
      y: 0,
      width: 39,
      height: 56,
      fill: "b",
      draggable: true
    });

leafer.add(rectCurrent);

var flag = {
  contents: 0
};

var flagTimeup = {
  contents: false
};

setInterval((function (param) {
        flagTimeup.contents = true;
        console.log("time up!");
      }), 200);

function rectUpdate(param) {
  if (flagTimeup.contents !== true) {
    return ;
  }
  flagTimeup.contents = false;
  flag.contents = Caml_int32.mod_(flag.contents + 1 | 0, fillContainer.length);
  var fill = fillContainer[flag.contents];
  rectCurrent.fill = fill;
  console.log("run update");
}

leafer.on_(LeaferUi.AnimateEvent.FRAME, (function (param) {
        rectUpdate(undefined);
      }));

function name(param) {
  return "my name is dragon";
}

var rectTimeDuration = 200;

export {
  leafer ,
  x_offset ,
  fillContainer ,
  fillx ,
  rectCurrent ,
  flag ,
  flagTimeup ,
  rectTimeDuration ,
  rectUpdate ,
  name ,
}
/* leafer Not a pure module */
