// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as LeaferUi from "leafer-ui";

var lf = new LeaferUi.Leafer({
      view: "mydiv"
    });

var lfadd = Curry._1(lf.add.bind, lf);

var re = new LeaferUi.Rect({
      x: 100,
      y: 100,
      width: 200,
      height: 200,
      fill: "#32cd79",
      draggable: true
    });

Curry._2(lfadd, re, undefined);
 