// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LeaferUi from "leafer-ui";

function main(param) {
  return "leafer-ui writting by rescript";
}

var leafer = new LeaferUi.Leafer({
      view: "mydiv"
    });

var re = new LeaferUi.Rect({
      x: 10,
      y: 10,
      width: 100,
      height: 100,
      fill: "#32cd29",
      draggable: true
    });

leafer.add(re);

export {
  main ,
  leafer ,
  re ,
}
/* leafer Not a pure module */
