// Generated by ReScript, PLEASE EDIT WITH CARE


x.onload = (function (v) {
    var o = this ;
    console.log(o.response + v | 0);
  });

function fun(a) {
  console.log(a);
}

console.log("hello");

var a = 101;

var a$1 = a + 2 | 0;

console.log(a$1);

export {
  fun ,
  a$1 as a,
}
/*  Not a pure module */
