// Generated by ReScript, PLEASE EDIT WITH CARE


function fun(a) {
  console.log(a);
}

console.log("hello");

var a = 101;

var a$1 = a + 2 | 0;

console.log(a$1);

var isRescript;

isRescript = "ReScript" === "ReScript" ? true : false;

console.log(isRescript);

function teststatic(param) {
  var local = 0;
  local = local + 100 | 0;
  return local;
}

console.log(teststatic(undefined));

console.log(teststatic(undefined));

var me = {
  age: 123,
  name: "ReScript"
};

export {
  fun ,
  a$1 as a,
  me ,
  isRescript ,
  teststatic ,
}
/*  Not a pure module */
